### ISSUE TITLE
W10 may 2020 update error

### ISSUE THREAD

**Issue by ole1105** [ManuelGil/Reset-Windows-Update-Tool#13]
Recently I updated my Windows 10 to 2004 version (may 2020 update), when I run this tool with option 2, it launchs next error.
![error](https://user-images.githubusercontent.com/33353160/83313249-b56c2d80-a215-11ea-826e-a35e06f49d87.png)

Script and executable version.

Thank you in advance.

**Comment by ManuelGil** [comment]
Hi @ole1105 

Thank you so much for reporting your issue.

I am going to do a clean install of Windows 10 2004 to try to replicate your error message.

As soon as I know more about it, I will inform you

**Comment by ManuelGil** [comment]
@ole1105 I've been testing and can't replicate your issue

![VirtualBox_Windows 10 x64_30_05_2020_00_23_58](https://user-images.githubusercontent.com/25472045/83320547-52c36380-a20e-11ea-99a0-1787734c4015.png)

Can you provide more information about it? please


What operating system did you come from?
Have you tried to repair your Windows installation with the DISM commands?

If you need information about Windows repair see: [Troubleshooting](https://github.com/ManuelGil/Reset-Windows-Update-Tool/wiki/Troubleshooting#dism-for-windows-8-windows-81-and-windows-10)

**Comment by ole1105** [comment]
I've got windows 10 (1909) before. Dism commands doesn't show error. 😕

I see, the problem is on my computer. I will try a clean install of windows 10 later, thank you for your support.
