### ISSUE TITLE
no support for XP

### ISSUE THREAD

**Issue by andika207** [ManuelGil/Reset-Windows-Update-Tool#15]
he bajado la supuesta versión para Windows XP pero ninguna de ellas funciona
http://wureset.com/downloads.php
https://gallery.technet.microsoft.com/scriptcenter/Reset-Windows-Update-Agent-d824badc

**Comment by ManuelGil** [comment]
El soporte de **Windows XP** finalizó el *8 de abril del 2014*, con lo cual los servidores con las actualizaciones de Windows XP se han ido apagando y por lo tanto dicho sistema ya no recibirá más actualizaciones.

Le herramienta de Restablecimiento de Windows Update en su versión en Script en español (`ResetWUSpa.cmd`) puede ser modificada para contener los comandos para el restablecimiento de componentes en Windows XP, sin embargo esto no garantiza que se reciban actualizaciones por parte de Microsoft.

**Comment by andika207** [comment]
@ManuelGil los servidores llevan apagados desde finales de Julio y el sabado pasado los reactivaron hasta ayer lunes, por alguna razón. Parece ser que hay un sistema de pago para empresas que seguirán recibiendo updates hasta 2025 y ahora con la filtración del codigo fuente seguro que algo bueno sacaremos...

**Comment by ManuelGil** [comment]
En efecto algunas distribuciones de tipo empresarial como son **Windows XP Embedded** seguirán recibiendo actualizaciones por su tipo de contrato dado que algunas entidades tienen estos sistemas en maquinas registradoras, por mencionar un ejemplo. Al una licencia activa con este tipo de contratos te puede asegurar la descarga e instalación de actualizaciones para estos equipos empresariales.

Por el momento solo te puedo recomendar hacer uso de la herramienta [`ResetWUEng.cmd`](https://github.com/ManuelGil/Script-Reset-Windows-Update-Tool/blob/master/ResetWUEng.cmd#L67) versión 10.5.3.7 que se encuentra aquí en *GitHub* ya que todavía cuenta con los comandos para restablecer los componentes de Windows Update en **Windows XP**, sin embargo reitero que no puedo garantizar la descarga e instalación de actualizaciones ya que dicho proceso depende de Microsoft.

**Comment by ManuelGil** [comment]
I hope this is helpful to you.

**Comment by andika207** [comment]
@ManuelGil por temas de salud entre otras cosas no pude analizar tu herramienta, ya lo haré en el proximo formateo... pero unos fanaticos de XP han sacado hace dos dias un parche para que XP pueda bajar los updates via SHA2 http://dl.free.fr/getfile.pl?file=/N2aPTeTs
