### ISSUE TITLE
01.11.2020 Setupdiag included in WUResetEng is outdated

### ISSUE THREAD

**Issue by Karl-WE** [ManuelGil/Reset-Windows-Update-Tool#19]
**Describe the bug**
setupdiag included is outdated and might throw unwanted or unhandled results

**To Reproduce**

check included setupfile.exe

**Expected behavior**
please update and release or eventually script a dynamic download
https://go.microsoft.com/fwlink/?linkid=870142

**Screenshots**
-- does not apply

**Desktop (please complete the following information):**

-- does not apply

**Additional context**
-- does not apply

**Comment by Karl-WE** [comment]
applies to version 18.11.2019
https://gallery.technet.microsoft.com/scriptcenter/Reset-Windows-Update-Agent-d824badc

**Comment by ManuelGil** [comment]
Hi @Karl-WE,

The TechNet Gallery will be retired, therefore the code posted there is deprecated and will not be updated.

I have done an update on [https://wureset.com](https://wureset.com/downloads.html), where I removed the standalone diagnostic tool.

You can also find this update on [GitHub](https://github.com/ManuelGil/Script-Reset-Windows-Update-Tool).

**Comment by Karl-WE** [comment]
@ManuelGil may i propose you are marking the git as retired?
https://github.com/ManuelGil/Reset-Windows-Update-Tool/wiki

**Comment by ManuelGil** [comment]
@Karl-WE, I don't understand your request.

The [`wiki`](https://github.com/ManuelGil/Reset-Windows-Update-Tool/wiki) is the official documentation for this tool and is constantly maintained.

**Comment by Karl-WE** [comment]
Alright. I think I looked somewhere else. Never mind.
